/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    FenceStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJNI_FenceStart
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     TestJNI
 * Method:    FenceEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TestJNI_FenceEnd
  (JNIEnv *, jobject);

/*
 * Class:     TestJNI
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNI_getLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
